require_relative './challenges.rb'

#LEVEL 2 BODY PHYSICAL CHALLENGE PAIN ENDURANCE

#BODY
flipadelphia = Challenge.new(title: "Flipadelphia", level: 2, category: "Body", prompt: "All play, a team relay race using standard flip cup rules. Single Elimination in the case of multiple teams.")
kitten_mittens = Challenge.new(title: "Kitten Mittens", level: 2, category: "Body", prompt: "Player must fit four tiny mittens on a cat’s feet. While this is happening, player’s teammate must chug. Player can only stop chugging when all four mittens are on the cat.")
kramer = Challenge.new(title: "Kramer", level: 2, category: "Body", prompt: "Kramer chug a beer (smoking a cigarette while downing a beer).")

#PHYSICAL CHALLENGE

acrobatics = Challenge.new(title: "Acrobatics", level: 2, category: "Physical Challenge", prompt: "Successfully flip a lit cigarette into your mouth, with the right end out, in five attempts or fewer. No sneezing, coughing, choking, or vomiting or you lose the challenge.")
push_up_challenge = Challenge.new(title: "Push Up Challenge", level: 2, category: "Physical Challenge", prompt: "Push-ups until you either drop or your team finishes a pitcher of beer. Push-ups should be done non-stop, only allowing for 2 seconds of rest in between each push-up.")
plank_challnge = Challenge.new(title: "Plank Challenge", level: 2, category: "Physical Challenge", prompt: "Plank until you either drop or team finishes a pitcher of beer.")
grape_gobble = Challenge.new(title: "Grape Gobble", level: 2, category: "Physical Challenge", prompt: "Pour a bucket of grapes across a table. One contestant from each team attempts to pick up as many grapes in seven seconds as possible without using hands. Contestant with the most grapes able to be shown wins (vomiting them counts).")
dizzy_bat = Challenge.new(title: "Dizzy Bat", level: 2, category: "Physical Challenge", prompt: "player has 45 seconds to place his/her forehead on a bat on the ground, spin around ten times with the bat staying in place, then walk to a table 5 paces away and chug a full beer, no vomiting.")
dayman = Challenge.new(title: "Dayman", level: 2, category: "Physical Challenge", prompt: " Sing “Dayman” (See Appendix B) while chugging beer. No card is awarded; instead, you may take the card of another person. Reminder: If you spit up/vomit during this challenge, you are responsible for making up the lost liquid. It is recommended to chug while your teammate does the background vocals. (if everyone else is still on MIND, you can still take a card from them to hinder progress. If the card is from Level 2 or 3, taking the card will make it yours). See Appendix B for Lyrics.")
nightcrawlers = Challenge.new(title: "NightCrawlers", level: 2, category: "Physical Challenge", prompt: "Each team nominates one player to have hands duct-taped behind back and legs duct taped together to compete in a caterpillar race. Players decide on course beforehand.")
fresh_prince = Challenge.new(title: "Fresh Prince", level: 2, category: "Physical Challenge", prompt: " Must do five handstand pushups (can use the wall or teammate to help balance) while drinking a beer through a straw. No card if you do not EITHER finish your beer or complete the five pushups.")
chubby_bunny = Challenge.new(title: "Chubby Bunny", level: 2, category: "Physical Challenge", prompt: "One player from each team must stuff their mouth with as many marshmallows as possible to play a game of “Chubby Bunny.” Each player only has 2 chances to say it, and choking then failing to say it results in a disqualification.")
occifer_plz = Challenge.new(title: "Occifer Pls", level: 2, category: "Physical Challenge", prompt: "Player takes a sobriety field test by walking one foot in front of the other 10 paces in a straight line (use painter’s tape), turn, and return to the start point.")
we_can_do_it = Challenge.new(title: "We Can Do It", level: 2, category: "Physical Challenge", prompt: "Two players from each team stand 5 paces from one another and play catch with a can of beer using their off-hand. After 30 seconds, all players cut the distance in half. Losers must open the cans of beer near their face.")
relay = Challenge.new(title: "Relay", level: 2, category: "Physical Challenge", prompt: "All Play: All teams engage in a relay race. Teams run a set route (around the block, for example) and must consume a full beer before/during/after. Team that finishes beer AND footrace first wins.")

#PAIN

fraternity = Challenge.new(title: "Fraternity", level: 2, category: "Pain", prompt: "Choose one member of the opposing team to strike your ass with a ruler. Please keep your underwear on. No flinching. If no ruler is available, a bucket can substitute.")
five_cereals = Challenge.new(title: "Name 5 Cereals", level: 2, category: "Pain", prompt: "Any member of the opposing team gives you a purple nurple and will not let go until you name five or tap out.")
the_mcpoyle_chug = Challenge.new(title: "The McPoyle Chug", level: 2, category: "Pain", prompt: "one player from each team must drink as much milk as they can. Player that drinks the most without vomiting wins for his/her team. Losers must remove their clothes and wear only underwear and a bathrobe for the duration of the game (or complete another challenge to get their clothes back) If they do not have a bathrobe, they must wear only underwear until the next challenge. Players are not punished for vomiting.")
five_star = Challenge.new(title: "Five Star", level: 2, category: "Pain", prompt: "A member of the opposing team gets to five star you. In order to obtain this card, you must not flinch or show signs of pain.")
william_tell = Challenge.new(title: "The William Tell", level: 2, category: "Pain", prompt: "The Player who Draws this Card must Place an Apple on their Head (A Solo cup may be used as a last minute substitution), their Teammate must walk 5 paces from them and then Turn. They must then attempt to knock the Apple off with a Tennis Ball. No flinching. A miss with no Flinch = Teammates Switch. Game continues until Apple is knocked off or a Flinch occurs.")
vomit = Challenge.new(title: "Vomit", level: 2, category: "Pain", prompt: "Vomit.")
hoppity_hop = Challenge.new(title: "Hoppity Hop", level: 2, category: "Pain", prompt: " All Play: Each player grabs a pillow and hops on one foot. No grabbing/grappling other players or pillows. Physical contact expected. Last man/team standing on one foot wins.")
ice_bucket_challenge = Challenge.new(title: "Ice Bucket Challenge", level: 2, category: "Pain", prompt: "Ice bucket challenge with clothes on. Alternatively, player may donate $50 to ALS Association (alsa.org)")
firing_squad = Challenge.new(title: "Firing Squad", level: 2, category: "Pain", prompt: " All Play: Player who drew this card stands 5 paces away from everyone else. At least one player from each team must chug a beer and throw the can at the player—the player’s eyes must always remain open. If the player flinches, he loses. During chance to steal, beer must still be consumed.")
not_a_game_a_war = Challenge.new(title: "Its not a game, its a war.", level: 2, category: "Pain", prompt: "Player must shotgun a beer then place his/her forehead on a bat on the ground, spin around 21 times and slap a teammate in the face. If teammate flinches or player misses, teammates switch places. Maximum 3 attempts total.")
dollar_shave_club = Challenge.new(title: "Dollar Shave Club", level: 2, category: "Pain", prompt: "Opponent applies a 6-inch strip of duct tape to anywhere on the player’s body that is not the head to remove hair.")
duel = Challenge.new(title: "Duel", level: 2, category: "Pain", prompt: "One player from each team holds a can of beer and stands back-to-back. Each player then begins to chug their beer at the same time. Upon finishing the beer, the player then quickly takes five paces and throws the empty beer can at the opponent. Last man standing wins. In the event that there are more than two teams, players may decide if there will be a Mexican stand-off or whether it will be a double elimination. Two cans per person encouraged for Mexican stand-off.")

#ENDURANCE

for_your_health = Challenge.new(title: "For Your Health", level: 2, category: "Endurance", prompt: "All Play: Whichever team can smoke the most cigarettes in two minutes wins the card. Cigarettes must the same brand and type and must be smoked to the filter.")
hot_potato = Challenge.new(title: "Hot Potato", level: 2, category: "Endurance", prompt: "One player from each team pass around the hot potato with only underhand throws. When it is just one player from each team remaining, the hot potato is replaced with a flaming tennis ball which has been soaked in a flammable alcohol of your choosing. Winning team gets to pelt the loser with the hot potato until it is mush. If there are many teams, the last two teams must flip a coin to figure out who the winner will pelt.")
michael_phelps = Challenge.new(title: "Michael Phelps", level: 2, category: "Endurance", prompt: "All Play: Whichever Team can hold their Breath the Longest Wins this Card. Passing out is a disqualification. Opposing player should hold onto one another’s noses to prevent cheating.")
helicopter = Challenge.new(title: "Helicopter", level: 2, category: "Endurance", prompt: " One player from each team spins. Players on the sideline may yell out ‘faster’ and you have to comply. Last man spinning after a minute wins.")
burn_notice = Challenge.new(title: "Burn Notice", level: 2, category: "Endurance", prompt: "One player from each team holds onto a match. All matches are lit at the same time. Last person to hold onto the match wins. (Tip: light all matches at the same time with an already lit match)")
hydration = Challenge.new(title: "Hydration", level: 2, category: "Endurance", prompt: "Chug a bottle of water faster than an opponent. You choose your opponent.")
dragons_breath = Challenge.new(title: "Dragon's Breath", level: 2, category: "Endurance", prompt: " Take a shot of Sriracha. You may not drink anything to ease the pain until the next event is over.")
nena = Challenge.new(title: "Nena", level: 2, category: "Endurance", prompt: "Team of player who drew this card must keep a balloon up in the air until their next turn to earn this card.")
